### PR TITLE
CenterNet code cleanup

### PR DESCRIPTION
**Pull request by hyingho**
Added the following changes to the CenterNet example.

## Bugfixes
* Fixed import errors.
* Fixed missing arguments.

## Code cleanup
* Removed unused files.
* Removed unused imports.
* Removed unused variables.
* Fixed typos.

### CODE REVIEW

**Comment by hyingho** [comment]
@yuikosakuma1 Would you please check and merge this PR?

**Comment by hyingho** [comment]
I will fix some auto format issues before the merge.

**Comment by hyingho** [comment]
@yuikosakuma1 Hi, I did some auto format. Would you please check this PR again and merge it?

**Review by yuikosakuma1 — APPROVED** [review]
These changes look good to me

**Pull request merged**
